services:
  sdknet:
    image: sdknet
    container_name: sdk_container
    ports:
      - 5000:5000
      - 5001:5001
    tty: true
  api: 
    image: api-async
    container_name: api-container
    ports: 
      - 8000:80
  sql:
    image: server-sql
    container_name: sql-container
    ports:
      - 1433:1433
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd
